### ISSUE TITLE
Backend is not detecting new multisig vaults  for co-signers and creator too.

### ISSUE THREAD

**Issue by subhod-i** [aeternity/ga-multisig-backend#12]
Right now the SH wallet's newly created multisig vaults are in a syncing state infinitely because the multisig backend API returns an empty array or doesn't include new vaults created.

Eg: As you see in Explorer the signers are present: https://explorer.testnet.aeternity.io/contracts/transactions/ct_FtuGsDvzcZnWDwnnfSjKLy1eL993gxLWpt157iD2LQG43znDV

but https://ga-multisig-backend-testnet.prd.aepps.com/ak_2BhSyb9o6k9bikgTn5b6ADTbhbFW5oamfiC8KbeeuUaze1hDNs
 return incorrect data.

**Comment by thepiwo** [comment]
should be fixed in https://github.com/aeternity/ga-multisig-backend/releases/tag/v1.1.1 I did reset the signers db so it will take a few minutes to be back up-to-date

**Comment by subhod-i** [comment]
> should be fixed in https://github.com/aeternity/ga-multisig-backend/releases/tag/v1.1.1 I did reset the signers db so it will take a few minutes to be back up-to-date

Just to confirm the existing signers would be restored right? @thepiwo

**Comment by thepiwo** [comment]
@subhod-i yes, they will be restored from on-chain data, just did this in case some where not indexed in previous version
